// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlTQcDCEGPU36hzaHkDxaOYMrAKO9AXso',
    appId: '1:444927888009:web:ebe393174afa74e5401458',
    messagingSenderId: '444927888009',
    projectId: 'officefinance-a4079',
    authDomain: 'officefinance-a4079.firebaseapp.com',
    storageBucket: 'officefinance-a4079.appspot.com',
    measurementId: 'G-CLW9LMX3RK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo83qGOPE9GU_fhujzF9QEoMctSHIj3wI',
    appId: '1:444927888009:android:084c6cf07a0510c7401458',
    messagingSenderId: '444927888009',
    projectId: 'officefinance-a4079',
    storageBucket: 'officefinance-a4079.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq_PHHJWMv3ElxU5BvBK5WYjh3B0A3DxQ',
    appId: '1:444927888009:ios:0b7029397b62bb99401458',
    messagingSenderId: '444927888009',
    projectId: 'officefinance-a4079',
    storageBucket: 'officefinance-a4079.appspot.com',
    iosBundleId: 'com.example.officeFinancesWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq_PHHJWMv3ElxU5BvBK5WYjh3B0A3DxQ',
    appId: '1:444927888009:ios:21d386cd44e97f96401458',
    messagingSenderId: '444927888009',
    projectId: 'officefinance-a4079',
    storageBucket: 'officefinance-a4079.appspot.com',
    iosBundleId: 'com.example.officeFinancesWeb.RunnerTests',
  );
}
